version: 0.2

env:
  variables:
    CF_TEMPLATE: "cloudfomation_template.yaml"
    CF_GUARD_POLICY:  "policy.guard"
phases:
  install:
    commands:
      - apt-get update
      - apt-get install build-essential -y
      - apt-get install cargo -y
      - apt-get install git -y
  pre_build:
    commands:
      - echo "Setting up the environment for AWS CloudFormation Guard"
      - echo "More info https://github.com/aws-cloudformation/cloudformation-guard"
      - echo "Install Rust"
      - curl https://sh.rustup.rs -sSf | sh -s -- -y
  build:
    commands:
       - echo "Pull GA release from github"
       - echo "More info https://github.com/aws-cloudformation/cloudformation-guard/releases"
       - wget https://github.com/aws-cloudformation/cloudformation-guard/releases/download/2.1.3/cfn-guard-v2-ubuntu-latest.tar.gz
       - echo "Extract cfn-guard"
       - tar xvf cfn-guard-v2-ubuntu-latest.tar.gz .
       - echo "Validate CloudFormation template with cfn-guard tool"
       - cfn-guard validate --rules $CF_GUARD_POLICY  --data $CF_TEMPLATE --output-format json > cfn_guard_output.json
  post_build:
    commands:
      - echo Uploading reports to S3
      - aws s3 cp cfn_guard_output.json s3://<bucket_name>/securityfingdings/cfn_guard_output.json